services:
  kobra-back-app:
    build: .
    container_name: kobra-back-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@kobra-back-db:5432/postgres
    depends_on:
      - kobra-back-db
  kobra-back-db:
    image: postgres:alpine
    container_name: kobra-back-db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - kobra-db-data:/var/lib/postgresql/data
volumes:
  kobra-db-data:
